server:
  port: 8889

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    check-template: true
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 500MB      # 单个文件大小（Mb和Kb都可以）
      max-request-size: 2048MB  # 连续上传文件大小
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  mail:
    default-encoding: utf-8
    # 主机地址
    host: smtp.163.com
    # 邮箱名
    username: luckkun123@163.com
    # 授权码（不是密码）
    password: EWVEDVMFWUECKAQE
    #设置协议及端口
    protocol: smtps
    port: 465

#mybatis:
#  mapper-locations: classpath:com/mapper/xml/*.xml
#  type-aliases-package: com.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zk/mybatisplus/**/*Mapper.xml

openHttps: close #关闭https

swagger:
  enable: true  #启动swagger
